# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
#  Compile:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: Set up JDK 11
#        uses: actions/setup-java@v1
#        with:
#          java-version: 11
#
#      - name: Generate Wrapper
#        run: gradle wrapper
#
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#
#      - name: Build with Gradle
#        run: ./gradlew compileJava

  Test:
#    needs: Compile
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: mkdir -p path/to/artifact

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Generate Wrapper
        run: gradle wrapper

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test with Gradle & Junit 5
        run: ./gradlew test

      - uses: actions/upload-artifact@v2
        with:
          name: testReport
          path: path/to/artifact/test/TEST-GameTest.xml


#  Assemble:
#    needs: Test
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: Set up JDK 11
#        uses: actions/setup-java@v1
#        with:
#          java-version: 11
#
#      - name: Generate Wrapper
#        run: gradle wrapper
#
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#
#      - name: Assemble with the Gradle Wrapper
#        run: ./gradlew assemble