# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
    tags:
      - v*.*
  pull_request:
    branches: [ main ]

jobs:
#  Compile:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: Set up JDK 11
#        uses: actions/setup-java@v1
#        with:
#          java-version: 11
#
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#
#      - name: Build with Gradle
#        run:  ./gradlew compileJava

  Test:
#    needs: Compile
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Gradle packages and Junit 5
        id: gradle-cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test with Gradle & Junit 5
        run: ./gradlew test

#      - name: Check current dir
#        run: ls -al ./build/reports/tests/

      - uses: actions/upload-artifact@v2
        with:
          name: testReport
          path: ./build/reports/tests/test

      - name: Cleanup Gradle Cache
        # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
        # Restoring these files from a GitHub Actions cache might cause problems for future builds.
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties

#  Assemble:
#    needs: Test
#    runs-on: ubuntu-latest
#
#    outputs:
#      output_filename: ${{ steps.jar_filename.outputs.temp }}
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#
#      - name: Set up JDK 11
#        uses: actions/setup-java@v1
#        with:
#          java-version: 11
#
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#
#      - name: Assemble with the Gradle Wrapper
#        run: ./gradlew assemble
#
#      - name: Set environment jar_filename
#        run: |
#          echo "jar_filename=$(ls ./build/libs/)" >> $GITHUB_ENV
#
#      - id: jar_filename
#        run: echo "::set-output name=temp::${{ env.jar_filename }}"
#
#      - uses: actions/upload-artifact@v2
#        with:
#          name: assembleJar
#          path: ./build/libs/
#
#  Realease:
#    needs: Assemble
#    runs-on: ubuntu-latest
#    if: ${{ startsWith(github.ref, 'refs/tags/') }}
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#
#      - uses: actions/download-artifact@v2
#        with:
#          name: assembleJar
#          path: ./download/artifacts
#
##      - name: Display file names
##        run: echo ${{needs.Assemble.outputs.output_filename}}
#
#      - name: Release
#        uses: softprops/action-gh-release@v1
#        with:
#          files: ./download/artifacts/${{needs.Assemble.outputs.output_filename}}
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}